version: "3.8"

services:
  web:
    image: multistage-build
    ports:
      - "5001:5001"
    depends_on:
      - mydb

  mydb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
